# Generated by Django 5.0.6 on 2025-01-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('quarter', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=10)),
                ('field_of_study', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('talent_1', models.CharField(max_length=50)),
                ('talent_2', models.CharField(blank=True, max_length=50)),
                ('talent_3', models.CharField(blank=True, max_length=50)),
                ('gift_1', models.CharField(blank=True, max_length=50)),
                ('gift_2', models.CharField(blank=True, max_length=50)),
                ('gift_3', models.CharField(blank=True, max_length=50)),
                ('orphant', models.BooleanField(default=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
            ],
        ),
    ]
